### ISSUE TITLE
Exception in thread Thread-5

### ISSUE THREAD

**Issue by aix4c** [azlux/MumbleRadioPlayer#17]
play - <a
href="http://stream.srg-ssr.ch/m/rsp/mp3_128">http://stream.srg-ssr.ch/m/rsp/mp3_128</a>
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "./mumbleRadioPlayer.py", line 81, in message_received
    self.play_stream(parameter)
  File "./mumbleRadioPlayer.py", line 151, in play_stream
    self.launch_play_stream(get_url(msg))
  File "./mumbleRadioPlayer.py", line 156, in launch_play_stream
    info = get_server_description(url)
  File "./mumbleRadioPlayer.py", line 253, in get_server_description
    data = json.loads(response.read().decode("utf-8"))
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 22622 (char 22621)

**Comment by azlux** [comment]
Hi, 
can you add after the line 252 of MumbleRadioPlayer.py : 
`print(response.read().decode("utf-8"))` and give me the output.

If not, I will debug that during next week. (I cannot debug myself the week-end)

**Comment by aix4c** [comment]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "./mumbleRadioPlayer.py", line 81, in message_received
    self.play_stream(parameter)
  File "./mumbleRadioPlayer.py", line 149, in play_stream
    self.launch_play_stream(url)
  File "./mumbleRadioPlayer.py", line 156, in launch_play_stream
    info = get_server_description(url)
  File "./mumbleRadioPlayer.py", line 253, in get_server_description
    print(response.read().decode("utf-8"))
  File "/usr/lib64/python3.4/encodings/koi8_r.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 12897: character maps to <undefined>

**Comment by azlux** [comment]
Can you try this fix ?
I think your stream don't produce valide json data.
Az
