### ISSUE TITLE
Exception in thread Thread-8

### ISSUE THREAD

**Issue by aix4c** [azlux/MumbleRadioPlayer#18]
play - <a
href="http://direct.dps-fm.com:8800/stream">http://direct.dps-fm.com:8800/stream</a>
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "./mumbleRadioPlayer.py", line 81, in message_received
    self.play_stream(parameter)
  File "./mumbleRadioPlayer.py", line 151, in play_stream
    self.launch_play_stream(get_url(msg))
  File "./mumbleRadioPlayer.py", line 156, in launch_play_stream
    info = get_server_description(url)
  File "./mumbleRadioPlayer.py", line 254, in get_server_description
    title_server = data['icestats']['source'][0]['server_name'] + ' - ' +
data['icestats']['source'][0]['server_description']
KeyError: 0

**Comment by aix4c** [comment]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "./mumbleRadioPlayer.py", line 81, in message_received
    self.play_stream(parameter)
  File "./mumbleRadioPlayer.py", line 149, in play_stream
    self.launch_play_stream(url)
  File "./mumbleRadioPlayer.py", line 156, in launch_play_stream
    info = get_server_description(url)
  File "./mumbleRadioPlayer.py", line 253, in get_server_description
    data = json.loads(response.read().decode("utf-8"))
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 23109 (char 23108)

**Comment by aix4c** [comment]
47025f4ac0540433be30c202946f0236  mumbleRadioPlayer.py

**Comment by Lartza** [comment]
That error is the same as in #17 and not related to this one which I fixed, Azlux just needs to merge the fix. Use the other issue for any additional info related to that issue. This issue was way more trivial than #17 and I haven't had time to look into that yet
