### ISSUE TITLE
MumbleRadioPlayer Launch Error

### ISSUE THREAD

**Issue by ADAMPOKE111** [azlux/MumbleRadioPlayer#2]
When launching MumbleRadioPlayer I get this error, despite having setup everything as described.

```
Traceback (most recent call last):
  File "./mumbleRadioPlayer.py", line 15, in <module>
    import pymumble
  File "./pymumble/pymumble/__init__.py", line 3, in <module>
    from mumble import Mumble
  File "./pymumble/pymumble/mumble.py", line 12, in <module>
    import users
  File "./pymumble/pymumble/users.py", line 4, in <module>
    import soundqueue
  File "./pymumble/pymumble/soundqueue.py", line 6, in <module>
    import opuslib
  File "/usr/local/lib/python2.7/dist-packages/opuslib/__init__.py", line 26, in <module>
    from .classes import Encoder, Decoder  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/opuslib/classes.py", line 11, in <module>
    import opuslib.api.decoder
  File "/usr/local/lib/python2.7/dist-packages/opuslib/api/__init__.py", line 20, in <module>
    'Could not find opus library. Make sure it is installed.')
Exception: Could not find opus library. Make sure it is installed.
```

**Comment by azlux** [comment]
So I suppose you found your opus library problem !

**Comment by ADAMPOKE111** [comment]
Yeah, it turned out to be an issue where the script I have written to install ffmpeg, avtools, opus etc. didn't actually install the opus library for some odd reason.

**Comment by AlexEshoo** [comment]
I'm having the same problem on launch, I've found a few other people online who've experienced problems with opus across multiple applications but no answers, did you do anything special to install the package? I used pip and it appears to be installed, but it simply doesn't work when imported.

**Comment by azlux** [comment]
@AlexEshoo : it's a python3 application, Think about install requirement with pip3 : https://github.com/azlux/pymumble#requirementsinstallation

**Comment by AlexEshoo** [comment]
I think I installed something wrong the first go around, I reinstalled it all and I have it working now.
