### ISSUE TITLE
Problem with shoutCAST url

### ISSUE THREAD

**Issue by hacknisty** [azlux/MumbleRadioPlayer#6]
Hi,

Install was done today following instructions on README.md

Trying to play shoutcast url with mumbleradioplayer always fail with : 

play - techno by Elkoxon
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./mumbleRadioPlayer.py", line 79, in message_received
    self.play_stream(parameter)
  File "./mumbleRadioPlayer.py", line 144, in play_stream
    self.launch_play_stream(url)
  File "./mumbleRadioPlayer.py", line 151, in launch_play_stream
    info = get_server_description(url)
  File "./mumbleRadioPlayer.py", line 235, in get_server_description
    response = urllib.request.urlopen(request)
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib64/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.5/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ICY 404 Resource Not Found

shoutcast provide .pls file, and by looking inside the pls file i get a streaming URL : http://audio.teknoradio.nl:8064/

This URL works in browser, also work with ffmpeg on command line (extracted from py script at line 160)

I've tried various stuff to bypass the error with no luck.

It's really hard today to find a web radio not running with shoutcast.

Best regards,

**Comment by azlux** [comment]
Ho, that not a issue from the stream but from the function who get the server stream name.
I'll check that.
Thank for your feedback

**Comment by azlux** [comment]
Can you confirm the problem is solved ?

**Comment by hacknisty** [comment]
Hi, problem is solved now ! Thanx a lot for this fast answer.

Best regards,

**Comment by azlux** [comment]
It was because the souhcast version of this stream is outdated. The link to have the server name isn't the same.
